#!/usr/bin/env python3
"""Trace register entries to the commits that implement them, from git trailers.

    trace.py <path to docs/architecture> [--write] [--strict] [--repo PATH]

Commits carry the claim; the registers stay clean:

    Archirules-Phase: P11
    Archirules-ADR: 0010
    Archirules-OQ: 05

**Git history is the truth and this script derives a view of it.** A commit SHA written
into a register by hand is duplicated state that starts lying at the first rebase, squash
or cherry-pick — which is exactly what these checkers exist to police, so the method does
not get to do it either.

`--write` regenerates `traceability.md` and records the commit it was generated at. The
default is to check, which is three claims:

  1. **No trailer names an entry that does not exist.** Same class as a dangling reference
     to a decision record, and the one gate here that is always safe to enforce.
  2. **The file is a faithful regeneration as of the commit it records.** Recomputed at that
     commit and byte-compared, so a hand-edited or half-updated view is a finding.
  3. `--strict` only: **no closed phase is without a commit, and the file is not behind
     HEAD.** Off by default — see OQ-07. A repository whose history predates this mechanism
     cannot satisfy it, and a gate that everybody has to switch off teaches people to switch
     gates off.

Exit 0 when nothing is wrong, 1 otherwise, 2 for a usage error.
"""
import os
import re
import subprocess
import sys

TRAILERS = {"phase": "Archirules-Phase", "adr": "Archirules-ADR", "oq": "Archirules-OQ"}
GENERATED = "traceability.md"
PHASE_FILES = ("fazy-realizacji.md", "phases.md")
MARKER = "<!-- GENERATED by trace.py — do not edit. Regenerate: trace.py <register> --write -->"


def die(message):
    print("  %s" % message, file=sys.stderr)
    raise SystemExit(2)


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def git(repo, *args):
    """Run git and refuse on failure. A gate must not read an error as an empty result."""
    run = subprocess.run(("git", "-C", repo) + args, capture_output=True, text=True)
    if run.returncode != 0:
        die("git %s failed: %s" % (" ".join(args), run.stderr.strip() or run.returncode))
    return run.stdout


def entries(directory):
    """What the registers contain: {'phase': {...}, 'adr': {...}, 'oq': {...}}."""
    found = {"phase": {}, "adr": set(), "oq": set()}
    for name in PHASE_FILES:
        path = os.path.join(directory, name)
        if os.path.isfile(path):
            for pid, status in re.findall(
                r"^\|\s*([A-Za-z]\w*)\s*\|[^|]*\|\s*([☐◐☑⛔][^|]*)\|", read(path), flags=re.M
            ):
                found["phase"][pid] = status.strip()
            break
    decisions = os.path.join(directory, "decisions")
    if os.path.isdir(decisions):
        for fname in sorted(os.listdir(decisions)):
            match = re.match(r"ADR-(\d{4})", fname)
            if match and fname.endswith(".md"):
                found["adr"].add(match.group(1))
    questions = os.path.join(directory, "open-questions.md")
    if os.path.isfile(questions):
        found["oq"] = set(re.findall(r"^### OQ-(\d+)\s+[—–-]\s", read(questions), flags=re.M))
    return found


def commits(repo, rev):
    """[(sha, subject, {kind: [value, ...]})] newest first, for every commit up to rev."""
    raw = git(repo, "log", rev, "--format=%H%x1f%s%x1f%b%x1e")
    out = []
    for record in raw.split("\x1e"):
        record = record.strip("\n")
        if not record:
            continue
        sha, subject, body = (record.split("\x1f") + ["", ""])[:3]
        claims = {}
        for kind, trailer in TRAILERS.items():
            values = []
            for line in re.findall(r"^%s:\s*(.+)$" % re.escape(trailer), body, flags=re.M):
                values += [v.strip() for v in line.split(",") if v.strip()]
            if values:
                claims[kind] = values
        out.append((sha, subject, claims))
    return out


def normalise(kind, value):
    """`ADR-0006`, `0006` and `6` are one entry; so are `OQ-05` and `5`."""
    if kind == "phase":
        return value.strip()
    digits = re.sub(r"\D", "", value)
    return digits.zfill(4) if kind == "adr" else digits.zfill(2)


def collect(found, history):
    """({kind: {entry: [(sha, subject)]}}, [problems]) — unknown entries are problems."""
    known = {
        "phase": set(found["phase"]),
        "adr": set(found["adr"]),
        "oq": {normalise("oq", q) for q in found["oq"]},
    }
    mapping = {kind: {} for kind in TRAILERS}
    problems = []
    for sha, subject, claims in history:
        for kind, values in claims.items():
            for value in values:
                entry = normalise(kind, value)
                if entry not in known[kind]:
                    problems.append(
                        "%s: %s: %s names %s, which is not in the register"
                        % (sha[:7], TRAILERS[kind], value, entry)
                    )
                    continue
                mapping[kind].setdefault(entry, []).append((sha, subject))
    return mapping, problems


def render(found, mapping, at):
    """The generated file, as text. Deterministic: same history in, same bytes out."""
    lines = [
        "# Traceability — registers to commits",
        "",
        MARKER,
        "",
        "Derived from `Archirules-*` trailers in commit messages. **The git history is the",
        "truth; this file is a view of it.** A commit identifier written into a register by",
        "hand starts lying at the first rebase — see ADR-0010.",
        "",
        "Generated at commit `%s`." % at,
        "",
        "## Phases",
        "",
        "| Phase | Status | Commits |",
        "|---|---|---|",
    ]
    for pid, status in found["phase"].items():
        claimed = mapping["phase"].get(pid, [])
        cell = " · ".join("`%s`" % sha[:7] for sha, _ in claimed) if claimed else "—"
        lines.append("| %s | %s | %s |" % (pid, status, cell))

    for kind, title, prefix in (("adr", "Decision records", "ADR-"), ("oq", "Open questions", "OQ-")):
        lines += ["", "## %s" % title, ""]
        claimed = mapping[kind]
        if not claimed:
            lines.append("No commit claims one yet.")
            continue
        lines += ["| Entry | Commits |", "|---|---|"]
        for entry in sorted(claimed):
            cell = " · ".join("`%s`" % sha[:7] for sha, _ in claimed[entry])
            lines.append("| %s%s | %s |" % (prefix, entry, cell))

    untraced = [pid for pid, status in found["phase"].items()
                if status.startswith("☑") and pid not in mapping["phase"]]
    lines += ["", "## Closed phases no commit claims", ""]
    if untraced:
        lines += [
            "These closed before commit tracing existed, or their commits carry no trailer.",
            "The list is expected to shrink and never to grow.",
            "",
        ]
        lines += ["- %s" % pid for pid in untraced]
    else:
        lines.append("None. Every closed phase is claimed by at least one commit.")
    return "\n".join(lines) + "\n"


def recorded_commit(text):
    found = re.search(r"^Generated at commit `([0-9a-f]{7,40})`\.$", text, flags=re.M)
    return found.group(1) if found else None


def main(argv):
    positional = [a for a in argv if not a.startswith("--")]
    flags = {a for a in argv if a.startswith("--")}
    repo = None
    for arg in argv:
        if arg.startswith("--repo="):
            repo = arg.split("=", 1)[1]
    for flag in flags:
        if flag not in ("--write", "--strict") and not flag.startswith("--repo="):
            die("unknown option: %s" % flag)
    directory = positional[0] if positional else "docs/architecture"
    if not os.path.isdir(directory):
        die("no such register directory: %s" % directory)
    repo = repo or git(directory, "rev-parse", "--show-toplevel").strip()

    found = entries(directory)
    if not found["phase"]:
        die("no phase table found in %s; nothing to trace" % directory)

    head = git(repo, "rev-parse", "HEAD").strip()
    path = os.path.join(directory, GENERATED)

    if "--write" in flags:
        mapping, problems = collect(found, commits(repo, head))
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(render(found, mapping, head))
        print("  written: %s · generated at %s" % (path, head[:7]))
        for problem in problems:
            print("    x %s" % problem)
        return 1 if problems else 0

    problems, notes = [], []
    mapping, problems_all = collect(found, commits(repo, head))
    problems += problems_all

    if not os.path.isfile(path):
        problems.append("%s does not exist; run trace.py %s --write" % (GENERATED, directory))
    else:
        text = read(path)
        at = recorded_commit(text)
        if not at:
            problems.append("%s records no commit it was generated at" % GENERATED)
        else:
            # Recompute AS OF that commit. Comparing against HEAD instead would make the
            # file stale the moment it is committed, and a gate nobody can satisfy is a
            # gate everybody switches off.
            past_mapping, _ = collect(found, commits(repo, at))
            if render(found, past_mapping, at) != text:
                problems.append(
                    "%s is not a faithful regeneration at %s — it was hand-edited, or the "
                    "registers changed since; run trace.py %s --write"
                    % (GENERATED, at[:7], directory)
                )
            newer = [sha[:7] for sha, _, claims in commits(repo, "%s..%s" % (at, head)) if claims]
            if newer:
                message = ("%s is behind HEAD: %d commit(s) with trailers since %s"
                           % (GENERATED, len(newer), at[:7]))
                (problems if "--strict" in flags else notes).append(message)

    untraced = [pid for pid, status in found["phase"].items()
                if status.startswith("☑") and pid not in mapping["phase"]]
    if untraced:
        message = "closed phases no commit claims: %s" % ", ".join(untraced)
        (problems if "--strict" in flags else notes).append(message)

    claimed = sum(len(v) for v in mapping.values())
    print("  traced entries: %d · problems: %d%s"
          % (claimed, len(problems), "" if "--strict" in flags else " · strict checks off"))
    for note in notes:
        print("    ~ %s" % note)
    for problem in problems:
        print("    x %s" % problem)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
